### ISSUE TITLE
Cool module

### ISSUE THREAD

**Issue by deysmusic** [nongthaihoang/san_francisco_plus_font#2]
I wish you added style Semibold, и main bold.

**Comment by nongthaihoang** [comment]
What are "semibold" and "main bold"? And for what?

**Comment by deysmusic** [comment]
> What are "semibold" and "main bold"? And for what?

I am Russian and would like to add a font module style semibold

**Comment by nongthaihoang** [comment]
I understand that you want something unusual but I already give the option to use medium style so there's no point for your "semibold". And one more thing Android (Roboto) does not have semibold style.
